{% set name = "scikit-survival" %}
{% set version = "0.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_survival-{{ version }}.tar.gz
  sha256: 24523748338aef8bd076850e4ad6257387b4547a6cf7b2a35776b535048de84d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - cython
    - numpy
    - pip
    - scikit-learn >=1.4.0,<1.5
    - setuptools_scm
    - packaging
    - python
  run:
    - python
    - scikit-learn >=1.4.0,<1.6
    - ecos
    - joblib
    - numexpr
    - osqp !=0.6.0,!=0.6.1
    - pandas >=1.0.5
    - scipy >=1.3.2

test:
  imports:
    - sksurv
    - sksurv.datasets
    - sksurv.ensemble
    - sksurv.io
    - sksurv.kernels
    - sksurv.linear_model
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebp/scikit-survival
  summary: Survival analysis built on top of scikit-learn
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - sebp
    - janjagusch
    - xhochy
