{% set name = "scikit-survival" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-survival-{{ version }}.tar.gz
  sha256: ba49325f6a31e8bdccfb88337aa85218d209e88a6a704e9c41ef13bf749e0f46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - cython
    - numpy
    - pip
    - scikit-learn >=0.24.0,<0.25
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn >=0.24.0,<0.25
    - ecos
    - joblib
    - numexpr
    - osqp !=0.6.0,!=0.6.1
    - pandas >=0.25
    - scipy >=1.0,!=1.3.0

test:
  imports:
    - sksurv
    - sksurv.datasets
    - sksurv.ensemble
    - sksurv.io
    - sksurv.kernels
    - sksurv.linear_model
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebp/scikit-survival
  summary: Survival analysis built on top of scikit-learn
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
