{% set name = "scikit-survival" %}
{% set version = "0.24.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scikit_survival-{{ version }}.tar.gz
  sha256: a388a6c55c7f8abee67de7a701437ec6b0520af400be6bd144ad0a501dbb2363

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - cython
    - numpy
    - pip
    - scikit-learn >=1.6.1,<1.7
    - setuptools
    - setuptools_scm
    - packaging
    - python
  run:
    - python
    - scikit-learn >=1.6.1,<1.7
    - ecos
    - joblib
    - numexpr
    - osqp !=0.6.0,!=0.6.1
    - pandas >=1.4.0
    - scipy >=1.3.2

test:
  imports:
    - sksurv
    - sksurv.datasets
    - sksurv.ensemble
    - sksurv.io
    - sksurv.kernels
    - sksurv.linear_model
    - sksurv.meta
    - sksurv.svm
    - sksurv.tree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sebp/scikit-survival
  summary: Survival analysis built on top of scikit-learn
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - sebp
    - janjagusch
    - xhochy
