context:
  name: scikit-survival
  version: 0.27.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/scikit_survival-${{ version }}.tar.gz
  sha256: 5ee6677688f358107209a705c2cdf6f0ac5f711a3784b8c60376383b9e0f2bc3

build:
  number: 0
  script:
    - python -m pip install . -vv
  skip:
    - match(python, "<3.11")

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
  host:
    - cython
    - numpy
    - pip
    - if: match(python, "<3.14")
      then: scikit-learn >=1.6.1,<1.7
      else: scikit-learn >=1.7.0,<1.8
    - setuptools
    - setuptools_scm
    - packaging
    - python
  run:
    - python
    - scikit-learn >=1.8.0,<1.9
    - ecos
    - joblib
    - numexpr
    - osqp >=1.0.2
    - pandas >=2.2.0
    - scipy >=1.13.0
    - numpy >=2.0.0
tests:
  - python:
      imports:
        - sksurv
        - sksurv.datasets
        - sksurv.ensemble
        - sksurv.io
        - sksurv.kernels
        - sksurv.linear_model
        - sksurv.meta
        - sksurv.svm
        - sksurv.tree

about:
  homepage: https://github.com/sebp/scikit-survival
  summary: Survival analysis built on top of scikit-learn
  documentation: https://scikit-survival.readthedocs.io
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - sebp
    - janjagusch
    - xhochy
